[tool.ruff]
line-length = 100
target-version = "py312"
lint.select = ["E", "F", "I", "B", "UP", "SIM", "PERF", "RUF"]

[tool.mypy]
python_version = "3.12"
strict = true
warn_unused_ignores = true

[tool.pytest.ini_options]
addopts = "-q --cov=."


